### ISSUE TITLE
cpa 'calle nro, Buenos Aires' no funciona? 

### ISSUE THREAD

**Issue by etagwerker** [djanowski/cpa#1]
[etagwerker@gesell ~]$ cpa 'Roma 659, Buenos Aires'
/Users/etagwerker/.rvm/gems/ruby-1.9.2-p180@cpa/gems/cpa-0.0.1/bin/cpa:62:in `initialize': No such file or directory - db/B (Errno::ENOENT)
    from /Users/etagwerker/.rvm/gems/ruby-1.9.2-p180@cpa/gems/cpa-0.0.1/bin/cpa:62:in`open'
    from /Users/etagwerker/.rvm/gems/ruby-1.9.2-p180@cpa/gems/cpa-0.0.1/bin/cpa:62:in `parse'
    from /Users/etagwerker/.rvm/gems/ruby-1.9.2-p180@cpa/gems/cpa-0.0.1/bin/cpa:89:in`<top (required)>'
    from /Users/etagwerker/.rvm/gems/ruby-1.9.2-p180@cpa/bin/cpa:19:in `load'
    from /Users/etagwerker/.rvm/gems/ruby-1.9.2-p180@cpa/bin/cpa:19:in`<main>'

**Comment by djanowski** [comment]
```
$ cpa 'Lavalleja 800, Capital Federal'
$ cpa 'Lavalleja 800, CABA'
```

Debería funcionar con 'Buenos Aires'?

**Comment by etagwerker** [comment]
No sé, esperaba que funcionara con BA. No ví docs, ví algo de código y parecía que tenía en cuenta a la pcia de BA. No es así?

**Comment by djanowski** [comment]
Ah!

Había dos problemas. Uno ya está arreglado, deberías actualizar la gema.

El otro es que tenés que poner la localidad antes de la provincia: `cpa 'Roma 659, Olivos, Buenos Aires'`

**Comment by etagwerker** [comment]
Uhm.. Todavía no funciona. 

Mirá:

[etagwerker@gesell ~]$ gem list --local

**\* LOCAL GEMS ***

cpa (0.0.2)
net-http-persistent (1.8)
[etagwerker@gesell ~]$ cpa 'Roma 659, Olivos, Buenos Aires'
/Users/etagwerker/.rvm/gems/ruby-1.9.2-p180@cpa/gems/cpa-0.0.2/bin/cpa:62:in `initialize': No such file or directory - db/B (Errno::ENOENT)
    from /Users/etagwerker/.rvm/gems/ruby-1.9.2-p180@cpa/gems/cpa-0.0.2/bin/cpa:62:in`open'
    from /Users/etagwerker/.rvm/gems/ruby-1.9.2-p180@cpa/gems/cpa-0.0.2/bin/cpa:62:in `parse'
    from /Users/etagwerker/.rvm/gems/ruby-1.9.2-p180@cpa/gems/cpa-0.0.2/bin/cpa:89:in`<top (required)>'
    from /Users/etagwerker/.rvm/gems/ruby-1.9.2-p180@cpa/bin/cpa:19:in `load'
    from /Users/etagwerker/.rvm/gems/ruby-1.9.2-p180@cpa/bin/cpa:19:in`<main>'

¿Por qué será?
